### ISSUE TITLE
BAD NEWS! Doesn't work on Windows

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker-gui#10]
The default browser engine of wx.html2.WebView is [IE7-based](https://wxpython.org/Phoenix/docs/html/wx.html2.WebView.html). That's just too old to be able to render a model webmap. The Edge backend is not enabled by default for license issues (?).

![image](https://user-images.githubusercontent.com/7456117/125173761-e1830d80-e18e-11eb-945c-3d1da52731e5.png)

**Comment by HuidaeCho** [comment]
What was the problem with [Folium](http://python-visualization.github.io/folium/) again? Does it work on Windows?

**Comment by HuidaeCho** [comment]
Check this code from https://stackoverflow.com/a/62607111/16079666 (slightly modified) for native rendering of OpenStreetMap
```python
#!/usr/bin/env python3
# https://stackoverflow.com/a/62607111/16079666
import matplotlib.pyplot as plt
import numpy as np
import math
import requests
from io import BytesIO
from PIL import Image


def deg_to_num(lat_deg, lon_deg, zoom):
  lat_rad = math.radians(lat_deg)
  n = 2.0 ** zoom
  xtile = int((lon_deg + 180.0) / 360.0 * n)
  ytile = int((1.0 - math.log(math.tan(lat_rad) + (1 / math.cos(lat_rad))) / math.pi) / 2.0 * n)
  return (xtile, ytile)


def num_to_deg(xtile, ytile, zoom):
  n = 2.0 ** zoom
  lon_deg = xtile / n * 360.0 - 180.0
  lat_rad = math.atan(math.sinh(math.pi * (1 - 2 * ytile / n)))
  lat_deg = math.degrees(lat_rad)
  return (lat_deg, lon_deg)


def get_image_cluster(lat_deg, lon_deg, delta_lat,  delta_long, zoom):
    # for macOS only?
    #headers = {"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"}
    smurl = r"http://a.tile.openstreetmap.org/{0}/{1}/{2}.png"
    xmin, ymax =deg_to_num(lat_deg, lon_deg, zoom)
    xmax, ymin =deg_to_num(lat_deg + delta_lat, lon_deg + delta_long, zoom)

    Cluster = Image.new("RGB", ((xmax-xmin+1)*256-1, (ymax-ymin+1)*256-1))
    for xtile in range(xmin, xmax+1):
        for ytile in range(ymin,  ymax+1):
            try:
                imgurl = smurl.format(zoom, xtile, ytile)
                print("Opening: " + imgurl)
                imgstr = requests.get(imgurl)#, headers=headers)
                tile = Image.open(BytesIO(imgstr.content))
                Cluster.paste(tile, box=((xtile-xmin)*256, (ytile-ymin)*255))
            except:
                print("Couldn't download image")
                tile = None

    return Cluster


if __name__ == "__main__":
    a = get_image_cluster(38.5, -77.04, 0.02,  0.05, 13)
    fig = plt.figure()
    fig.patch.set_facecolor("white")
    plt.imshow(np.asarray(a))
    plt.show()
```

**Comment by ocsmit** [comment]
Wow. And there's a lot of manual steps which would be required to enable the Edge/Chromium backend. Maybe... If there are not any reliable work arounds maybe an electron based application using the JS API would be a better course of action. Though Im sure that would be significantly more work.

**Comment by HuidaeCho** [comment]
Not familiar with Electron. I'm trying to render OSM using wx.Image() without PIL or matplotlib.

**Comment by HuidaeCho** [comment]
At the same time, you can try Electron.

**Comment by HuidaeCho** [comment]
Removed `wx.html2` and added three standard modules: `math`, `urllib.request`, and `io`.

![image](https://user-images.githubusercontent.com/7456117/125176017-4134e500-e19e-11eb-827a-5c8dff6911e6.png)

**Comment by ocsmit** [comment]
> Removed `wx.html2` and added three standard modules: `math`, `urllib.request`, and `io`.
> 

I see this doesn't allow for user drawing however.

**Comment by HuidaeCho** [comment]
> I see this doesn't allow for user drawing however.

We'll implement it ourselves.

**Comment by ocsmit** [comment]
> > I see this doesn't allow for user drawing however.
> 
> We'll implement it ourselves.

Great! Will learn a lot from it.

**Comment by HuidaeCho** [comment]
Panning implemented in https://github.com/HuidaeCho/projpicker-gui/commit/1435a8ba415873d7bd409d2d8ff5df30011b41b8, but `wx.EVT_MOUSEWHEEL` and `wx.EVT_MOUSE_EVENTS` don't respond to wheeling (both mouse and ThinkPad TrackPoint) for zoom.

Well... at this point, I'm kind of disappointed with wxPython ;-).

**Comment by HuidaeCho** [comment]
Also, was not able to fix the window size.. I thought it was fixed, but now it's resizable. Maybe, it's a BSPWM thing.

**Comment by ocsmit** [comment]
I can confirm that is a BSPWM thing. It stays a fixed size on other desktop environments.

**Comment by HuidaeCho** [comment]
Going to try https://stackoverflow.com/a/33851761

**Comment by HuidaeCho** [comment]
https://wxpython.org/Phoenix/docs/html/wx.lib.statbmp.html

**Comment by ocsmit** [comment]
Possibility to replace the webview back end entirely https://github.com/cztomczak/cefpython. They explicitly mention and have an example of embedding in wxpython.

**Comment by HuidaeCho** [comment]
I knew about cefpython. Please try it on Windows and Linux. I can recycle my osm code in the core to show selected bbox.

**Comment by HuidaeCho** [comment]
For now, let's keep the current gui and create a new folder in experimental.

**Comment by HuidaeCho** [comment]
Moved `OpenStreetMapDownloader` to the core as `openstreetmap.OpenStreetMap`. It's GUI-framework agnostic. At least, that's my intention. Please try v.0.1.7.post2 from Windows.

![image](https://user-images.githubusercontent.com/7456117/125212632-e0300e80-e27c-11eb-8ce9-06b64c7e72d6.png)

**Comment by HuidaeCho** [comment]
Notice no true opacity in tkinter.

**Comment by HuidaeCho** [comment]
How is Electron going?

**Comment by HuidaeCho** [comment]
Now, at this point, I'm not sure if I'll be able to finish the JS version (just not enough time and very low return on investment; also, now query syntax is a lot more than when I first thought about pure-JS :-(), so let's take this opportunity to move from desktop-only to client/server for both desktop and web. What do you think? Would it be too much work to implement UI components in JS only? In the backend, we'll just pass messages between the client and projpicker. Let me know what you think.

**Comment by ocsmit** [comment]
> How is Electron going?

Working on getting a nice and pretty CSS/HTML layout set up while making sure we can easily write the required JS for the UI similar to what our current layout is. 

>  ... let's take this opportunity to move from desktop-only to client/server for both desktop and web. > What do you think? 

I personally think that is a good idea, and one that may lend itself to future portabilty. Now when you say client/server in this case, I am assuming you mean our back-end starting a local server (flask, bottle, etc.) and using the Python API, but correct me if I am wrong. I believe I now have enough passing knowledge in JS and how it interacts with the DOM to write UI code. And what I may not know, I know how to learn and what to look for.

**Comment by HuidaeCho** [comment]
Right. Very light web server and our wxPython-based web-view (Electron?) will be our *browser* for the desktop version. In this case, for security, we just allow desktop clients only (? or just server regular browsers as well? That's a design decision). When there are no desktop clients running, the backend becomes a web server and regular browsers will be able to access it.

**Comment by ocsmit** [comment]
If we are going to writing JS UI code and be doing all the necessary HTML/CSS templating, it would make sense to switch to [Electron](https://www.electronjs.org/) in my opinion. Electron is created solely for the use of web tech for desktop applications while WxPython will always be a sort of hacky implementation for our purposes so long as we are using a client/server model (and even before).

**Comment by HuidaeCho** [comment]
How heavy is Electron? I just know its name. What is it? Is it like a Python module that we can install very easily? `pip install electron`? What are we sacrificing by using Electron over wxPython?

**Comment by HuidaeCho** [comment]
For the new desktop GUI, I don't think we want to start our JS app in a regular browser. Instead, it would be a better user experience if the GUI would start just like a regular GUI program. Please do some research if that's possible with Electron.

**Comment by ocsmit** [comment]
Electron is an NPM package, not sure how heavy it may be at the moment. It does not start in the browser but starts like a normal desktop application, and it can be packaged using [electron-builder](https://github.com/electron-userland/electron-builder).

**Comment by HuidaeCho** [comment]
Do you think cefpython would be much easier and quicker to implement? Is it almost like a drop-in replacement?

**Comment by ocsmit** [comment]
I think on paper it would be easier and quicker to implement as it is the closest thing to drop in replacement we may find. However it comes with its own quirk as well. E.g. the cefpython needs to be started differently for different OS's (see [here](https://github.com/cztomczak/cefpython/blob/master/examples/wxpython.py)). It also is only able to work with Python <= 3.7.

**Comment by HuidaeCho** [comment]
* cefpython: supposedly quicker desktop GUI fix for Windows
* electron: one stone, two birds (desktop and web)

cefpython supports up to Python 3.9 (https://github.com/cztomczak/cefpython#latest-release). Still, I just don't like the idea of mixing UI in JS and Python. It was getting trickier per my experience. Anyway, it's really up to you because you're the first author of the GUI project and I'm just annoying you by making changes here and there ;-). I guess, you learned enough JS and my coding styles for JS and Python (through my refactoring commits) to ensure consistent coding.

I just want to make sure that the desktop GUI works on Windows by the end of July before you get too busy with your Ph.D. course work. I'll just play with the currently clunky tkinter OSM in the core ;-). That'll keep me busy.

**Comment by HuidaeCho** [comment]
And different start-up code for different OSs shouldn't be a factor in your decision because that only affects us, not users.

**Comment by ocsmit** [comment]
So this is interesting. The WxPython edge backend works for me and checking if it is available with
 ```python 
print(wx.html2.WebView.IsBackendAvailable(BACKEND))
```
returns true. 

All of the JavaScript functions are working as well within edge. However when running with WxPython the it seems to get hung up when "pushGeometryChunk" is called from the webview. In the webview console we can see only the first geometry chunk, and in the python console it does not progress beyond the first 'pull'.

![image](https://user-images.githubusercontent.com/55674113/125356604-6bb8a680-e334-11eb-8f54-bb730ca12887.png)

**Comment by ocsmit** [comment]
Also I have been trying to get cefpython to work but it does not appear it will be as easy of a replacement as it seemed at face value. Using it on my Linux machine meets me with only segfaults, even with their WxPython example and even with a clean python environment.

**Comment by HuidaeCho** [comment]
Got it. Now, our choice is very clear. Electron.

**Comment by HuidaeCho** [comment]
@ocsmit Please check how the core GUI works in version 0.1.9. Looks ugly and no pretty icons (my lack of interest), no partial zoom levels (tkinter limitation), no true transparency (tkinter limitation), but it works.

![image](https://user-images.githubusercontent.com/7456117/126086715-529508b1-92b5-444d-935b-14fe8c8fb3cc.png)

**Comment by HuidaeCho** [comment]
How is your R&D going?

**Comment by HuidaeCho** [comment]
Oh! Please update the ArcGIS toolbox to v0.1.9. `bbox = ppik.gui.select_bbox(bbox)` => `bbox, _, _ = ppik.gui.start(bbox=bbox)`.

**Comment by ocsmit** [comment]
The core GUI looks and works phenomenally.

As for flask app, slowly getting there. Code right now is dirty and is under the Electron branch. Still some bugs and more work very obviously needs to be done. Dynamically passing data between JS and Python can be a bit tricky at times but I believe the core is almost there after I debug some of the asynchronous functions and refactor. 

A lot has been read, tested, and learned. 

![image](https://user-images.githubusercontent.com/55674113/126087770-4da47818-2100-498d-8d7c-850b0d12a4eb.png)

**Comment by HuidaeCho** [comment]
Looks awesome! So this screenshot runs on Firefox! Does it have its desktop counterpart?

**Comment by ocsmit** [comment]
Not yet, but that is the plan for tomorrow. Get the current code packaged with electron, make it reproducible, then work on debugging / refactoring / adding more functionality.

**Comment by HuidaeCho** [comment]
So my understanding is that you just need to implement the client side of the desktop GUI using Electron's web view thing...

**Comment by ocsmit** [comment]
Switching away from Electron to [PyWebview](https://pywebview.flowrl.com/). It is lighter than Electron and will keep GUI within Python framework. Also removes need for NPM. About to test on Windows. 

Here it is running the current code on Linux. 

![image](https://user-images.githubusercontent.com/55674113/126192780-5836c32e-68e0-4739-b4fc-8caaf96fe172.png)

**Comment by ocsmit** [comment]
Windows works.

![image](https://user-images.githubusercontent.com/55674113/126196901-575681be-16ff-43e0-a1f1-b1917efbf18e.png)

**Comment by ocsmit** [comment]
Out of curiosity, I reverted back to an older commit (ea608fd4437852b3cd70a96d157e09725453eec7) and set the backend to Edge with 

```python
self.browser = wx.html2.WebView.New(self.panel, backend=wx.html2.WebViewBackendEdge)
```
and well... it works without any issues. Going to do some more digging.

![image](https://user-images.githubusercontent.com/55674113/126229684-c9ccf784-7665-40df-a95f-0ab1773f67d3.png)

**Comment by ocsmit** [comment]
WxPython webview stops working with Edge backend after commit 7ae2a197eddac3310552a0a953383de81527dea6. This is when the better method (but still hacky) method of pulling the geometry chunks was introduced.

**Comment by HuidaeCho** [comment]
In my installation on Windows, `wx.html2.WebView.IsBackendAvailable(wx.html2.WebViewBackendEdge)` returns `False` and the GUI crashes on startup if I try to use the Edge backend. My wxPython version is 4.1.1. Do you have a different version? How did you install your wxPython? I used pip install.

**Comment by HuidaeCho** [comment]
![image](https://user-images.githubusercontent.com/7456117/126233128-29dbdda5-82ba-436d-ae6c-85fcc75299de.png)

**Comment by HuidaeCho** [comment]
To run the electron branch, I installed webview and flask.
```bash
$ pip install webview
Collecting webview
  Downloading webview-0.1.5.tar.gz (18 kB)
Building wheels for collected packages: webview
  Building wheel for webview (setup.py) ... done
  Created wheel for webview: filename=webview-0.1.5-cp37-cp37m-linux_x86_64.whl size=28260 sha256=0bdb1ad7e74776cdd1f2bcfddd14881120ee39b645a40af3e0e3722f39b0914c
  Stored in directory: /home/user/.cache/pip/wheels/b2/29/b5/701ba246e357f8de5204097cad550ed26878c550d8a28e4dc1
Successfully built webview
Installing collected packages: webview
Successfully installed webview-0.1.5

$ pip install flask
Collecting flask
  Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 1.4 MB/s 
Requirement already satisfied: click>=7.1.2 in /home/user/usr/local/lib/python3.7/site-packages (from flask) (7.1.2)
Collecting Werkzeug>=2.0
  Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 11.5 MB/s 
Collecting Jinja2>=3.0
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 15.0 MB/s 
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp37-cp37m-manylinux2010_x86_64.whl (31 kB)
Installing collected packages: MarkupSafe, Werkzeug, Jinja2, itsdangerous, flask
Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 Werkzeug-2.0.1 flask-2.0.1 itsdangerous-2.0.1
```
But, I'm getting this error:
```bash
$ python main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    window = webview.create_window('ProjPicker', server)
AttributeError: module 'webview' has no attribute 'create_window'
```
Did I install the wrong webview module?

**Comment by HuidaeCho** [comment]
Related?
* https://github.com/r0x0r/pywebview/issues/321

But we don't have webview.py in the branch.

**Comment by ocsmit** [comment]
It is `pip install pywebview`

**Comment by HuidaeCho** [comment]
Ah.. many webviews.. Then, I installed PyQt5. Now, getting this error:
```bash
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/user/usr/local/lib/python3.7/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/user/usr/local/lib/python3.7/site-packages/webview/platforms/gtk.py", line 25, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/user/usr/local/lib/python3.7/site-packages/webview/platforms/qt.py", line 38, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView, QWebEnginePage as QWebPage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/usr/local/lib/python3.7/site-packages/webview/guilib.py", line 29, in import_qt
    import webview.platforms.qt as guilib
  File "/home/user/usr/local/lib/python3.7/site-packages/webview/platforms/qt.py", line 43, in <module>
    from PyQt5 import QtWebKitWidgets
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' (/home/user/usr/local/lib/python3.7/site-packages/PyQt5/__init__.py)
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    webview.start(debug=True)
  File "/home/user/usr/local/lib/python3.7/site-packages/webview/__init__.py", line 96, in start
    guilib = initialize(gui)
  File "/home/user/usr/local/lib/python3.7/site-packages/webview/guilib.py", line 93, in initialize
    raise WebViewException('You must have either QT or GTK with Python extensions installed in order to use pywebview.')
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
```
`pip install gi` doesn't install anything with this message:
```bash
ERROR: Could not find a version that satisfies the requirement gi (from versions: none)
ERROR: No matching distribution found for gi
```

**Comment by HuidaeCho** [comment]
Easier way to install all the required modules?

**Comment by ocsmit** [comment]
On my Arch Linux machine I had to install the [python-pywebview](https://aur.archlinux.org/packages/python-pywebview/) package and on their installation page they give instructions for installing on  Ubuntu which requires a couple additional packages as well. On windows I had to use the [pythonnet](https://github.com/pythonnet/pythonnet) whl file at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet to be able to install all the dependencies. 

That is too many steps to be intuitive.

**Comment by HuidaeCho** [comment]
> That is too many steps to be intuitive.

I agreed. That's just too much for regular GIS users. If not `pip install` especially for Windows, I wouldn't say it's an easy installation. Even for Linux, not all users have root rights to be able to install a package. This is bad...

Let's do this. If we cannot implement the desktop GUI with easy pip installs, let's forget about the desktop GUI and just implement the server-side code and HTML+JS files. Then, through arguments, we give the user an option to start it as a web server only and another option to start it as a web server and open the browser locally using the standard [webbrowser](https://docs.python.org/3/library/webbrowser.html) module. I think all this desktop webview development sounds too heavy. What do you think?

**Comment by HuidaeCho** [comment]
Of course, we can keep already developed code for more advanced users.

**Comment by HuidaeCho** [comment]
And in the worst case, we can just use the core GUI for desktop. It requires no installation at all. I even skipped partial zooming because that would require Pillow.

**Comment by HuidaeCho** [comment]
For the server code, it would still be great if we implemented it only using standard modules.

**Comment by ocsmit** [comment]
I think that is better course of action. The more I have been trying to integrate various web-views into a coherent desktop application the more discouraged I get. 

Plus the core GUI is fantastic itself.

**Comment by ocsmit** [comment]
@HuidaeCho see https://github.com/HuidaeCho/projpicker/tree/web-experimental

It functions the same as what I had been doing with flask but using standard modules. Its not complete but getting there.

**Comment by HuidaeCho** [comment]
Cool. Let me test it.

For the core GUI, tile rescaling is implemented. When you zoom, rescale old tiles first and download new tiles in the background. Need more testing.

**Comment by HuidaeCho** [comment]
One comment: https://docs.python.org/3/library/http.server.html#module-http.server

> Warning http.server is not recommended for production. It only implements basic security checks. 

Also, we'll have to think about HTTPS with self-signed certificates and, of course, regular certificates as well.

**Comment by HuidaeCho** [comment]
https://security.stackexchange.com/questions/226095/pythons-http-server-library-basic-security-checks

**Comment by HuidaeCho** [comment]
Let's close this issue now. It's irrelevant.
