### ISSUE TITLE
Implement GetOSM in WxPython

### ISSUE THREAD

**Issue by ocsmit** [HuidaeCho/projpicker-gui#15]
The next logical continuation is the implementation of [GetOSM](https://github.com/HuidaeCho/getosm/) in WxPython to provide native rendering of OSM tiles. This would *hopefully* address issues faced by WxPython html2 backend on Windows. It will also allow potential further integration with GRASS GIS (https://github.com/OSGeo/grass/issues/1253#issuecomment-887528334).

Other things to consider: 
- Backup *low res* tiles for offline usage?
  -  Possibly one of the tiles in the GRASS GIS global dataset sample data 
- Any sort of usage limitations on OSM's side?

**Comment by HuidaeCho** [comment]
* Low res tiles are very quick to download, so I don't think we need to backup those tiles. If anything, a better caching management needs to be implemented, but for now, I didn't see any major issues.
* *Maybe* it would be good to implement that smooth zooming transitioning between zoom levels. This is impossible using the standard library because image rescaling is limited to 2**z where z is an integer. wxPython supports fractional rescaling. Theoretically, it could be implemented in tkinter, but it would take multiple passes of integer zoom() and subsample(), which can be *very* inefficient.
* We can start from [osmwx](https://github.com/HuidaeCho/getosm/blob/master/getosm/osmwx.py).

**Comment by ocsmit** [comment]
Forgot it also had Wx code already. So then the main functionality which would need to be added would be drawing and querying from osmwx.

**Comment by HuidaeCho** [comment]
Ideally, it would be best to exactly replicate the same layout, features, and shortcuts in the core GUI to avoid confusions, but we can always add more features (icons in the map, smooth transitioning), but not less.

**Comment by HuidaeCho** [comment]
I thought about this. Is it really necessary? We'll have to maintain two different GUIs in the end. What can we do better with wxPython that cannot be done with tkinter? I think this consideration is important.

I guess, if we just want to do this merely for the sake of using the same GUI framework as GRASS for *seamless* integration (only possible when using wxPython?), I don't think it's a good idea in the long term.

Will the core GUI look very alienated if it's integrated as part of GRASS? If so.. I think this effort might be worth it. Or if we can implement nice features using wxPython that we cannot using tkinter, definitely worth trying it.

**Comment by HuidaeCho** [comment]
This situation is just like the abandoned JS version, I think.

**Comment by HuidaeCho** [comment]
FYI, check https://github.com/HuidaeCho/projpicker/issues/44

**Comment by ocsmit** [comment]
I completely agree. I am working on the WxPython GUI right now and while it is fun and interesting to work on, it will be more code to maintain while the Tkinter GUI works seamlessly. Off the top of my head I can't think of anything which WxPython would offer that would make it an absolute necessity.

**Comment by HuidaeCho** [comment]
Oh! Already started! How long have you gone?

**Comment by ocsmit** [comment]
Not too long. I have replaced the webview with the static bitmap and am working on dynamic drawing to then query with projpicker right now. The Query builder, log, coordinate display, etc would still need to be implemented in WxPython which would most likely take time.

**Comment by HuidaeCho** [comment]
I see. The end of the official funding is near. Maybe https://github.com/HuidaeCho/projpicker/issues/43 then?

**Comment by HuidaeCho** [comment]
wxGUI wasn't too much of work. https://github.com/HuidaeCho/projpicker/commit/52da70d47c478afc6b0602fe3f09a6991311b4de Part of the core *only if* wxPython is installed. Otherwise, fall back to tkGUI.

**Comment by ocsmit** [comment]
That's great!
