### ISSUE TITLE
Support for geometry variables?

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker-gui#6]
How can we name geometries from the map? If possible, we can store geometries in variables and the user just types variable names and logic in the query builder. Then, when they run it, we preprend the variable definitions to the user query.
```
postfix
# define point geometries
UNG: 34.2348,83°52'3.72"W
Atlanta: 33°44'56.4",-84.3880

# query
:UNG
:Atlanta
xor
```

Check [the syntax](https://projpicker.readthedocs.io/en/latest/getting_started/query_syntax.html#geometry-variables) and [examples](https://projpicker.readthedocs.io/en/latest/usage_examples/querying_crss.html).

**Comment by HuidaeCho** [comment]
Oh! And now, it supports multiple geometries in one line. For spaces in a unit, `unit="US foot"` if mixed with other geometries in the same line. In this mode, spaces cannot be used to separate lat and lon unless they are enclosed with quotes.

**Comment by HuidaeCho** [comment]
Maybe, automatically insert variable names at the cursor location as well.

**Comment by HuidaeCho** [comment]
An idea.. In the query builder text control, type a variable name and select it (double click), then draw a geometry. We named it! No selection? Unnamed geometry is copied directly at the cursor.

Also, for this, when the user starts drawing a geometry, we automatically switch to the query builder.

Then, when a CRS is selected, again automatically switch to the CRS info.

**Comment by HuidaeCho** [comment]
See how the core GUI handles this.
* select name => :name: (save, use)
* select :name: => :name: (save, use)
* select name: => name: (save)
* select :name => :name (use)

**Comment by ocsmit** [comment]
The query builder is working as it should with all combinations I can think of trying between the four different operations. Also the query builder in general might be the most fun piece of tech i have interacted with. It is so flexible.

**Comment by HuidaeCho** [comment]
Also, the map never steals focus from other controls. This is useful especially when you type a query string in the text box and draw geometries and you can keep typing without refocusing.

**Comment by HuidaeCho** [comment]
Supported in the new wxgui
