### ISSUE TITLE
Coloring issue in BSPWM (only?)

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker-gui#8]
1. Start the GUI
2. Open any filter combo box and close it
3. Move the window

![image](https://user-images.githubusercontent.com/7456117/125167039-7c1e2500-e16c-11eb-862a-4ce2ff97be86.png)

**Comment by ocsmit** [comment]
I don't have this issue on my BSPWM build. Is anything printed to the console when this happens?

**Comment by HuidaeCho** [comment]
Nothing is printed. Window mode-related? floating, pseudo-tiled?

**Comment by ocsmit** [comment]
Tried tiled, psuedo-tiled, floating, monocled, etc. and still can't reproduce. What system theme is being used? Could it be a display manager (lightdm, gdm, ...) issue if one is present?

**Comment by HuidaeCho** [comment]
I'll check it later.

**Comment by HuidaeCho** [comment]
Closing. No more filter combo boxes and the web app is pure HTML+JS+CSS.
